name: Scrape
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install-python
        name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - id: install-pipenv
        name: Install pipenv
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
        shell: bash

      - id: cache-pipenv
        name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - id: sync-pipfile
        name: Sync pipfile
        run: pipenv install --dev --python=3.9
        shell: bash

      - id: download
        name: Download
        run: pipenv run python src/download.py

      - id: commit 
        name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./
          git commit -m "data update" && git push || true
        shell: bash

      - id: archive
        name: Archive to biglocalnews.org
        uses: biglocalnews/upload-files@main
        with:
          api-key: ${{ secrets.BLN_API_KEY }}
          project-id: ${{ secrets.BLN_PROJECT_ID }}
          path: data/iowa-liquor-stores.csv